"""initial

Revision ID: 1a9d911d4cbe
Revises: 
Create Date: 2026-05-29 17:10:12.622455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9d911d4cbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tailored_cvs', sa.Column('strategy', sa.String(length=20), nullable=True))
    op.add_column('tailored_cvs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tailored_cvs', 'created_at')
    op.drop_column('tailored_cvs', 'strategy')
    # ### end Alembic commands ###
